//
//  SwiftConfApp.swift
//
//  This file is automatically generated by SlideGen
//

import SlideKit
import SwiftUI

@main
struct SwiftConfApp: App {
	
	/// Edit slide configurations in SlideConfiguration.swift
	private static let configuration = SlideConfiguration()
	@StateObject var colorSchemeContainer = PresentationState()
	
	/// A presentation content view.
	/// Edit the view here if you'd like to set environments, overlay views or background views.
	var presentationContentView: some View {
		SlideRouterView(slideIndexController: Self.configuration.slideIndexController)
			.slideTheme(Self.configuration.theme)
	}
	
	var body: some Scene {
#if os(macOS)
		WindowGroup {
			PresentationView(slideSize: Self.configuration.size) {
				presentationContentView
					.modifier(ColorSchemeProvider())
					.modifier(ColorSchemeInverter())
					.modifier(WaterBreakModifier())
					.environmentObject(colorSchemeContainer)
			}
		}
		.setupAsPresentationWindow(Self.configuration.slideIndexController, appName: "SwiftConf")
		.addPDFExportCommands(for: presentationContentView, with: Self.configuration.slideIndexController, size: Self.configuration.size)
#endif
		WindowGroup {
			macOSPresenterView(
				slideSize: Self.configuration.size,
				slideIndexController: Self.configuration.slideIndexController
			) {
				presentationContentView
			}
			.modifier(ColorSchemeProvider())
			.modifier(ColorSchemeInverter())
			.modifier(WaterBreakModifier())
			.environmentObject(colorSchemeContainer)
		}
#if os(macOS)
		.setupAsPresenterWindow()
#endif
	}
}
